### ISSUE TITLE
Nan produced

### ISSUE THREAD

**Issue by susheelbhanu** [MGXlab/social_niche_breadth_SNB#4]
Hi, 

I'm trying to run the attached file and despite several combinations of c1 and c2 values, only Nans are produced. Any thoughts on why this might be the case?
[output_table.csv](https://github.com/user-attachments/files/16105889/output_table.csv)

Thanks,
Susheel

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @susheelbhanu,

The input file should be tab separated instead of comma separated. Could you try again with a tab separated file?
For reference, converting a comma separated file into a tab separated file can be done with `sed`:

`sed 's/,/\t/g' output_table.csv > output_table.tsv`

Please keep me updated! :)

Best wishes,

Bastiaan

**Comment by susheelbhanu** [comment]
Hi @bastiaanvonmeijenfeldt, 

Yeah I realised it after I posted the issue, based on your example in the readme. Seems to be working alright now. Any suggestions on what is a good way to identify cutoffs when using the --c1 and --c2 flags?

I've found that this is a little arbitrary at the moment and depending on the values, the SNB values change quite a bit. 

Thank you!

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @susheelbhanu,

You're right that these values are a bit arbitrary.

For future reference, the `--c1` parameter is the presence cut-off (default 1e-4). At the very least it should be set to the equivalent of 1 read in the most shallowly sequenced microbiome, to prevent biases due to large difference in sequencing depth. For example, if that sample contains only 100 reads, this parameter should be set at least to 1% (1e-2), as any microorganism with lower abundance than that would have been missed in that sample just because of the low sequencing depth.

The `--c2` parameter represents the cutoff for pairwise comparisons of two samples. You can also set it to a relative abundance cutoff (e.g. 1e-4) but we decided against this in the paper because you may discard a lot of relevant taxonomic information that you can use to quantify the distance between two samples being compared. For example, if you compare two very deeply sequenced microbiomes, discarding all taxa within the long tail of the rank-abundance curve because an other sample (that you're not comparing to) is less deeply sequenced is a waste of information. So in the paper we use an absolute abundance cut-off of 5 reads instead (the current default in the scripts on this repository). Of course, this may generate new biases when comparing deeply sequenced to shallowly sequenced microbiomes.

So the answer on how to pick these values depends on the data that you put in. Is there a difference in sequencing depth, or in alpha diversity between the samples? These parameters represent a lot of biological processes going on in a microbiome that we do not completely understand; how is microbial diversity generated and maintained, etc.

One way to deal with this is to run the script multiple times with slightly different parameter values, and see if you get similar results. The robustness of the biological results to parameter choice is something we used in the paper extensively. I expect primarily deviations on the edge of the detection limit, so for low-abundant organism (or low-abundant in a set of samples).

Hope this helps!

Bastiaan

**Comment by susheelbhanu** [comment]
Thanks @bastiaanvonmeijenfeldt that's kind of what I figured and in fact, ran it with multiple options, eventually choosing an average SNB score across the runs 😇. Not sure if that is kosher, but it seems to reflect the results obtained outside of the average scores. 

Thank you!
